### ISSUE TITLE
Property '0' does not exist on type '{}'.

### ISSUE THREAD

**Issue by Ristophonics** [MetaMask/vite-react-ts-eip-6963#2]
Any way to fix this problem? Thank you Team!

From DiscoverWalletProviders.tsx 

Full error : Element implicitly has an 'any' type because expression of type '0' can't be used to index type '{}'.
  Property '0' does not exist on type '{}'.

from `    try {
      const accounts = await providerWithInfo.provider
          .request({method:'eth_requestAccounts'})

      if(accounts?.[0]) {
        setSelectedWallet(providerWithInfo)
        setUserAccount(accounts?.[0])
      }
    } catch (error) {
      console.error("Failed to connect to provider:", error);
    }`

**Comment by chexovm** [comment]
Still having the same issue.
